[mongodb]
mongodb.nagalakshmi.site

[catalogue]
catalogue.nagalakshmi.site

[redis]
redis.nagalakshmi.site

[user]
user.nagalakshmi.site


[cart]
cart.nagalakshmi.site

[frontend]
frontend.nagalakshmi.site

[mysql]
mysql.nagalakshmi.site

[rabbitmq]
rabbitmq.nagalakshmi.site

[dispatch]
dispatch.nagalakshmi.site


[shipping]
shipping.nagalakshmi.site

# above all user this are the common variables
[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

