- name: configure {{ component }} component
  become: yes
  hosts: "{{ component }}"
  roles: # this will automatically load the floder called roles in current working directory
  - "{{ component }}"