# no need to write separate file we can parametraise the all componnets
- name: configure {{ component }} component
  become: yes
  hosts: "{{ component }}"
  roles: # this automatically load
  - "{{ component }}"


  # ansible-playbook -i inventory.ini -e component=mongodb main.yaml


