- name: install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: start mysql server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes
# this one give an error beaacuse if we gave here it is installed in nodes
# but we need to install in ansible server to get the password
# install manullay
- name: install boto3 and boto core
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - boto3
  - botocore

- name: setp root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1