 # here we need to import the common tasks from common floder
  - name: app setup
    include_role:
      name: common
      tasks_from: app-setup
 

  - name: node js setup
    include_role:
      name: common
      tasks_from: nodejs

# from this tasks this not common so we can keep here
  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present

  - name: check products loaded or not
    ansible.builtin.command: mongosh --host mongodb.nagalakshmi.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: print the catalogue output 
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: load the products
    ansible.builtin.command: mongosh --host mongodb.nagalakshmi.site < /app/db/master-data.js
    when: catalogue_output.stdout | int < 0
    # this is exmple for error handling we want skip anything if we know this wil give any_errors_fatal
    ignore_errors: true
  
  - name: system service
    include_role:
      name: common
      tasks_from: systemd
# it validate during runtime errors also come during the task execution
# tags are not apply here 
# 
  # - name: deployment setup
  #   tags: 
  #   - deployment
  #   include_role:
  #     name: common
  #     tasks_from: deployment 
  - name: deployment setup
    tags: 
    - deployment
    import_role:
      name: common
      tasks_from: deployment 
