  - name: install maven
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
      - maven
      - mysql

  - name: install PyMySQL and cryptography
    ansible.builtin.pip:
      name: "{{ item  }}"
      executable: pip3.9
    loop:
      - cryptography
      - PyMySQL

  - name: install maven dependies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: rename the jar file 
    ansible.builtin.command: "mv target/{{ component }}-1.0.jar shipping.jar"
    args:
      chdir: /app
