  - name: copy catalogue service to system directory
    ansible.builtin.template:
      src: catalogue.service.j2
      dest: /etc/systemd/system/catalogue.service

  - name: reaload the catalogue service
    ansible.builtin.systemd_service:
      daemon_reload: true 

  - name: start and enable the catalogue component
    ansible.builtin.service:
      name: catalogue
      state: restarted # app is not running we can always restart
      enable: yes